### ISSUE TITLE
[projects] support EcoRegistry credits in CarbonMark

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1016]
EcoRegistry built a blockchain native registry for quality carbon offsets. We want to bring these credits to Polygon and support them in our products, just like we support TCO2 and C3T tokens.

# Understanding EcoRegistry
- A credit holder can take credits in their EcoRegistry account and bridge them to a variety of blockchains, including Polygon with 1-click. This is already supported.
- When they choose to bridge to polygon, they sign an agreement saying these are _"no longer in their custody inside EcoRegistry and if they transfer those credits in that public blockchain, they can't get back those credits to Ecoregistry"_
- The tokens on Polygon should have all of the relevant project information associated with them.
- To officially retire credits they must be "bridged back" to EcoRegistry. However we were told this process can be completed instantly via API by the token holder.

We need to do more research on how this API works and the best way to support retirement.

## TODO (WIP)
This list is preliminary needs to be refined
* [ ] Form a complete picture of their system so we can decide on how these tokens are best integrated
  - contract methods, the "blocking" behavior and reverse-bridging API, and relevant events.
* [ ] Support these tokens in the retirement aggregator contracts (if possible)
* [ ] Get PNGs or SVGs for their native token icon
* [ ] Support in the following `site` pages:
  - [ ]  /retirement/[address]
  - [ ]  /retirement/[address]/[index]
  - [ ]  /pledge/[address]
* [ ] Support in the following `app` pages
  - [ ]  /#/offset
* [ ] Support in the following `CarbonMark` pages:
  - [ ]  /projects
  - [ ]  /projects/[id]
  - [ ]  /user/[handle]
  - [ ]  /portfolio
-

**Comment by Atmosfearful** [comment]
Will close this as the ticket is outdated. We can create a new one based on the new requirements defined more recently
