### ISSUE TITLE
[retirement] Integrate retire flow into carbonmark

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1126]
## Description

See the design [here in figma](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=0-1&t=O6juuQt7ejTkQ6PZ-0)

When a user wants to retire from a Single Project on carbonmark, the redirect to the [Offset screen on the app](https://app.klimadao.finance/#/offset) should be removed.
Instead, the retirement flow should happen directly on carbonmark.

## Todo
- [ ] integrate the [KlimaRetirementAggregatorV2 contract](https://github.com/KlimaDAO/klimadao/blob/staging/lib/abi/KlimaRetirementAggregatorV2.json) for retrieving data (cost, fees)
- [ ] build the UI (see design)
- [ ] Use the same contract for integrating the retirement transactions

**Comment by jabby09** [comment]
@ladytrekker moved this one to the retire epic https://github.com/KlimaDAO/klimadao/milestone/11

**Comment by ladytrekker** [comment]
### URL structure

- /projects/VCS-191-2008/retire/pools/bct
- => in getStaticProps check the prices array => get the matching price for "BCT" => render page

## Caching
- try getServerSideProps instead of getStaticProps and try revalidate with higher frequency
- => user should always get the latest price of this pool

## Price revalidation
The pool price can change every second.
- [ ] find a way to always get the latest price of a pool (SWR?)
