### ISSUE TITLE
[buy] Integrate Buy from pool flow into carbonmark

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1127]
## Description

See the design for the buy flow [here in figma](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F?node-id=11:59103#402372817)

When a user wants to buy tokens from a Single Project on carbonmark, the redirect to the [Redeem screen on the app](https://app.klimadao.finance/#/redeem) should be removed.
Instead, the buy/redeem flow should happen directly on carbonmark.

## Todo
- [x] integrate the [KlimaRetirementAggregatorV2 contract](https://github.com/KlimaDAO/klimadao/blob/staging/lib/abi/KlimaRetirementAggregatorV2.json) for retrieving data (cost, fees)
- [x] build the UI (see design)
- [x] Use the same contract for integrating the buy transactions

---

## FEEs Breakdown
From this [comment](https://github.com/KlimaDAO/klimadao/issues/990#issuecomment-1550305716):

### First, here is a top-level view of the fees to make sure we are all on the same page
Fees depend on which payment token, which pool, and how many tonnes are being retired.
|                                                                        | SushiSwap | Toucan | C3     | KlimaDAO RA |
|-------------------------------------------------|-------------|---------|--------|----------------|
| Swap to pool token<br>(per swap)              | 0.3%          |              |        |             |
| Default Redeem from any pool                     |              | 0%         | 0%       |             |
| Selective Redeem from BCT                          |                   | 25%        |        |             |
| Selective Redeem from NCT                          |                  | 10%        |        |             |
| Selective Redeem from UBO                          |                  |              | 2.5% |             |
| Selective Redeem from NBO                          |                  |              | 2.5% |             |
| Retire your own project token                        |                  |              |        | 0%        |
| Redeem & retire pooled token<br>(% IN TONNES***) |  |        |        | 1%***          |

#### Retire tco2/c3t you already own
No fees.
Why? The RA does not charge a fee if you are providing the project token to retire.

#### Buy tco2/c3t from 🏷️ seller listing
No fees.
Why? USDC goes directly to carbonmark contract. No swaps or redeems needed.

#### 'Retire Now' from 🏷️seller listing
No fees.
Why? Under the hood this is just a combination of both steps above (buy asset -> retire it)

#### 'Buy Now' from a 🤽pool listing.
No fees for the RA.
Sushi fees apply depending on # of swaps
Pool fees apply unless you are redeeming the default project.
Why?
Under the hood, the RA is doing a swap via sushi to get to the target pool token, then using the pool token to redeem the desired project from the pool. The RA does not charge for redeeming, it only charges for redeeming and retire.

#### 'Retire Now' from a 🤽pool listing.
Same as above, but with an additional 1% fee for the RA.

*** the 1% aggregator fee is calculated as 1% of the _tonnage being retired_.
For example, a default retirement of 1 tonne, paid for with BCT, adds a 0.01 BCT fee, for a total cost of 1.01 BCT
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/b546d367-06f1-4ce2-95f0-b86744be36cf)
Then, this value is converted to the payment token (for now, just USDC)

### Considering the above, there are a few challenges and open questions from my end
- To calculate the sushi fee, do we need to hardcode the # of swaps for each pair? For now this is fine as USDC is the only input token, and there are only a few destination tokens:
  - USDC -> MCO2 is 1 swap
  - USDC -> BCT is 2 swaps
  - However, when carbonmark adds support for other payment tokens, how many combinations will we need to support? Will we need to talk to Sushi directly to estimate the swap route?
- Do we need to hardcode the current default projects for each pool?
  - These do not pay a pool redemption fee
  - If we do hardcode, everything will break when supply of that particular project runs out.

**Comment by ladytrekker** [comment]
**URL structure**
- /projects/VCS-191-2008/purchase/pools/bct
=> in getServerSideProps check the prices array => get the matching price for "BCT" => render page

- compare URL to existing pruchase from seller listing: /projects/VCS-191-2008/purchase/<LISTING_ID>
