### ISSUE TITLE
[retire from project pool] Make pages accessible

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1189]
## Description

With this PR https://github.com/KlimaDAO/klimadao/pull/1169 the main work on "retire from project pool" is done.

You can access the pages here:

- **BCT** https://carbonmark.com/projects/VCS-191-2008/retire/pools/bct
- **UBO** https://carbonmark.com/projects/VCS-1140-2015/retire/pools/ubo

Still, the link from a project pool "Retire now" is still pointing to the main KlimaDao App.

## TODOs
- [x] Get the correct token address and pool price when these ticket are done => https://github.com/KlimaDAO/klimadao/issues/1160, https://github.com/KlimaDAO/klimadao/issues/1156#issuecomment-1568676421
- [ ] Is the price calculation from the API correct? See https://github.com/KlimaDAO/klimadao/issues/1156
- [ ] Double check the fee calculation again
- [ ] link the button "retire now" to the correct page
