### ISSUE TITLE
[retirements] Create overview of last five retirements

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1208]
## Retirements overview for address

**URL**
- `carbonmark.com/retire`

**New Design:**
- [FIGMA](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=627-5649&t=LotHihQMtZtL3FNw-0)

<img src="https://github.com/KlimaDAO/klimadao/assets/95881624/30d13bb7-7d0c-4d8f-92bc-709b98bc1fd5" width="600" />

## Log In Status
- [ ] Logged in only

## Technical requirements / Questions
- [ ] Status of the current address => What is the Matrix here ?? How de we know if an address is at place "426th" ??
- [ ] => OUT OF SCOPE !

## TODOs
- [x] On client: Check if logged in, show Log-in card otherwise
- [x] On client: Show loading spinner while getting all retirements, show empty state if none
- [x] On client: get the last five retirements 
- [x] On client: for each retirement get the corresponding project info
- [x] Render last five retirement infos
- [x] Link each retirement to retirement receipt in new tab => example [URL](https://www.carbonmark.com/retirements/0xab5b7b5849784279280188b556af3c179f31dc5b/2) 
- [x] Consider empty states !! Missing in designs (NOTED...professor working on this)
- [x] Link "View all retirements" => URL ?? (=> https://carbon.klimadao.finance/retirements/beneficiary)
- [x] Render status of the current address => OUT OF SCOPE

**Comment by jabby09** [comment]
@ladytrekker empty state [design](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=673-9125&t=q9MpV43tX7XeJZLA-4)

Note...subject to change with input from creative team

**Comment by ladytrekker** [comment]
@jabby09 @theprofessora 

Is it possible to just use the same components on the same page for all browser sizes?

I do not see the benefit of integrating special checks like (are you small, are you bigger) for rendering the same data in a completely different manner?

Or is there a special idea behind this retirement list being rendered as an activity (from a project pool design) instead?

### CURRENT FIGMA DESIGN

![Bildschirmfoto 2023-06-19 um 16 59 23](https://github.com/KlimaDAO/klimadao/assets/95881624/33b6e200-746d-47f2-8dcb-aab77ad74d3d)

### USE SAME COMPONENT INSTEAD

![Bildschirmfoto 2023-06-19 um 17 01 58](https://github.com/KlimaDAO/klimadao/assets/95881624/f9368074-1fa7-4c4f-814c-fd967116039e)

**Comment by theprofessora** [comment]
Hey there, good catch. The difference in designs between desktop and mobile view is intentional. Especially on very narrow phones, the data in the table becomes so crowded that it's hard to make any sense of the information presented. 

In the example above, imagine if the quantity column had a 3-digit value in one of the table cells. I think it would break the design.

I know it's extra work, but any time I've conducted usability tests with tables like this, the results indicate much easier use and interpretation of the important info when we make a special mobile view, like what we've mocked up in the figma
