### ISSUE TITLE
[retirements] Featured projects to retire

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1209]
## Retirements featured projects

**URL**
- `carbonmark.com/retire`

**New Design:**
- [FIGMA](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=627-5649&t=LotHihQMtZtL3FNw-0)

![fea](https://github.com/KlimaDAO/klimadao/assets/95881624/b4eb39b2-b5f6-416b-bf00-c55a2d6211cf)

## Log In Status
- [ ] Logged-in, Logged-out

## Technical requirements / Questions
- [x] featured projects are hardcoded => YES, for version 1
- [x] featured projects are coming from Carbonmark API ?? 
=> additional backend work such as "add a flag "isFeaturedProject" or alike, for version 2
- [x] How to link to each retirement? Are these always seller listings? Or pool prices too? Or simply the best price of this project (no matter if from seller or pool) ? => NO, go to project page
- [x] Or rather link to the Project page instead of a single retirement so the user can decide if "retire from seller listing" or "retire from pool" ?

## TODOs
- [x] On server: get the last three featured projects 
- [x] Render last three  featured projects 
- [x] Link each project single page 
- [ ] ~Design includes a "Back to retirements" button => may be difficult to achieve~

**Comment by Atmosfearful** [comment]
@jabby09 @sy-zygy just triple checking that these are the actual projects we want to feature. Can you confirm with drew

**Comment by jabby09** [comment]
@ladytrekker 

The featured project URL will be:

- https://www.carbonmark.com/projects/VCS-1577-2015
- https://www.carbonmark.com/projects/VCS-1764-2020
- https://www.carbonmark.com/projects/VCS-1121-2018
