### ISSUE TITLE
[retirements] Show Portfolio assets to retire from

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1210]
## Portfolio assets to retire from

**URL**
- `carbonmark.com/retire`

**New Design:**
- [FIGMA](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=627-5649&t=LotHihQMtZtL3FNw-0)

![Bildschirmfoto 2023-06-13 um 13 57 02](https://github.com/KlimaDAO/klimadao/assets/95881624/bca199fd-de3f-4f61-9919-d213af73d32a)

## Log In Status
- [ ] Works for logged-in users only

## TODOs
- [x] On client: check if user is logged in
- [x] Is logged in => show loading spinner
- [x] If logged-in user is not a carbonmark user => Show empty state message (Missing in design)
- [x] If logged-in user is a carbonmark user => from each asset get the corresponding project data (see Portfolio page for code references)
- [x] If logged-in user is a carbonmark user but has no assets => show empty state message ("Buy from Marketplace to retire your own tokens" ??)
- [x] Link each project to corresponding retirement page from PORTFOLIO. This URL for "Retire your own tokens" works for logged-in users only => URL `https://www.carbonmark.com/portfolio/<TOKEN_ADDRESS>/retire`
- [x] Design includes a "Back to retirements" button => may be difficult to achieve

**Comment by jabby09** [comment]
@ladytrekker @Atmosfearful 

@theprofessora already has a design to-do to mock up this section if either (1) not logged in, and (2) logged in but zero (empty state) or maybe 1 project asset

**Comment by jabby09** [comment]
@ladytrekker 

Not logged in state [design](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=732-8319&t=q9MpV43tX7XeJZLA-4)

Low # of assets [design](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=732-9844&t=q9MpV43tX7XeJZLA-4)
