### ISSUE TITLE
[retirements] Quick retire from default projects

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1211]
## Quick Retirements of default projects

**URL**
- `carbonmark.com/retire`

**New Design:**
- [FIGMA](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=627-5649&t=LotHihQMtZtL3FNw-0)

![Bildschirmfoto 2023-06-13 um 14 04 56](https://github.com/KlimaDAO/klimadao/assets/95881624/03af33d8-bb3c-4d24-84fc-77a6a11f578b)

## Log In Status
- [ ] Logged-in, Logged-out

## Technical requirements / Questions
- [x] default projects are hardcoded  => YES (create a lib file for the future! One Spot with an array)
- [ ] curated projects are coming from Carbonmark API ?? 
=> additional backend work such as "add a flag "isCuratedProject" or alike
- [x] How to link to each retirement => hardcode the path `projects/VCS-981-2014/retire/pools/<POOL>`

## TODOs
- [x] On server: get the last four default projects (one per pool)
- [x] Render last four default projects 
- [x] Link each project to retirement page form
- [x] Design includes a "Back to retirements" button => may be difficult to achieve

**Comment by jabby09** [comment]
@ladytrekker @Atmosfearful 

this section is meant to be the default projects in the pool, so not hardcoded. 
essentially this replaces the Default option on https://app.klimadao.finance/#/offset
