### ISSUE TITLE
[carbonmark] Pool purchase success - align Modal to figma design

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1215]
## Description

Comment from this PR https://github.com/KlimaDAO/klimadao/pull/1191
=> Replacing the Success Modal when "buying from pool" with actual static NEXTJS page (URL to be discussed)

**Relevant subgraph:**
https://thegraph.com/hosted-service/subgraph/klimadao/polygon-bridged-carbon

- Example [query](https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/graphql?query=query+MyQuery+%7B%0A++redeems%28%0A++++where%3A+%7B%0A++++++redeemer%3A+%220xd1a3699f2098ac92c2f4914979fcb22aba86d259%22%2C+%0A++++++transaction_%3A+%7B%0A++++++++id%3A+%220xcf7ac4f27858d0870bf21fa32e61f18b0606f3153c12d6bc26067f565ea17c1d%22%0A++++++%7D%0A++++%7D%0A++%29+%7B%0A++++id%0A++++transaction+%7B%0A++++++id%0A++++++blockHash%0A++++++value%0A++++%7D%0A++++pool%0A++++value%0A++%7D%0A%7D)
- => missing: total price, project

### **Success Modal when "buying from pool"**
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/7411d9e9-a978-4263-b317-d96e3e5c3ee8)

### **Compare with Receipt PAGE when "Buying from Seller Listing"**
- [FIGMA](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=11-59688&t=taQ8lJOsmXDfW8pu-4)

### Temporary success screen while the transactions are finalizing...

<img width="715" alt="Screenshot 2023-06-14 at 4 52 45 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/f5c8e231-c240-4e5d-9b0b-571bfe00619a">

### Full receipt when "Buying from Seller Listing"**
<img width="455" alt="Screenshot 2023-06-14 at 4 53 10 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/9fe1d33d-e8cf-44d5-8b2e-fbb144103537">

## Problem

When "Buying from a Seller Listing" the flow is as such:

The first screenshot above shows these checks on the server: 
- is the transaction hash in the URL valid? 
- If so, check if the Carbonmark API already has data for this purchase? 
- NO ? => render page with placeholder

The second screenshot above shows these checks on the server: 
- is the transaction hash in the URL valid? 
- If so, check if the Carbonmark API already has data for this purchase? 
- YES ? => render page with all data from Carbonmark API for this specific purchase ID

Because when buying from a seller listing, the transaction is an interaction with the carbonmark contract.
The purchase is saved on the Carbonmark API side and we can render a new static page late at any time (just pass the hash to the URL):
- GET purchase data from HASH => `api.carbonmark.com/api/purchases/<TXN_HASH>` [See an example page with data from Carbonmark API](https://www.carbonmark.com/purchases/0xcad9383fba33aaad6256304ef7b103f3f00b21afbaffbbff14423bf074b699e8)
- The carbonmark API provides all relevant data for this page **including the purchase price and the quantity**

Instead, when "Buying from a Pool " the flow is as such:

The redeem transaction is an interaction with the retirement aggregator contract.
There is no API for "give me all data from a pool purchase with transaction hash XYZ". 
Also the RA does not provide any method for that.
In this case, we would need to query the subgraph to create new static page for every transaction.
The query should give back: total price including fees, poolToken, quantity, project.

## TODO
- [ ] find out how to get all relevant data from a pool purchase 
- [ ] Depending on the needed inputs for this queries the final receipt page URL is constructed 
- => `carbonmark.com/purchases/pools/<TOKEN_ADDRESS>/<HASH>` ?
- => or `carbonmark.com/purchases/pools/<USER_ADDRESS>/<HASH>` ?
- [ ] create a new purchase page for nextJS (depending on URL structure above)
- [ ] Render the same receipt component as for "Buy from Seller Listing"

**Comment by jabby09** [comment]
this will be covered off by #2290
