### ISSUE TITLE
[carbonmark] Align all processing/loading spinners

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1216]
## Problem

There are different processing spinners in the designs and on different pages.
The new spinner is only implemented on one page so far.
This ticket is created because of this [comment here](https://github.com/KlimaDAO/klimadao/pull/1191#issuecomment-1592159186)

### Spinner old
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/e1a35707-fae5-4278-8ff8-5d807d3d6abc)
Spinner: https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/components/shared/Spinner/index.tsx
SpinnerWithLabel: https://github.com/KlimaDAO/klimadao/tree/staging/carbonmark/components/SpinnerWithLabel

### Spinner new
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/034253d6-cbc3-46ca-9fae-c230c79e02d1)
See only implementation here: 
https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/components/pages/Retire/RetireModal/index.tsx#L114
=> SO FAR ONLY IMPLEMENTED FOR "RETIRE FROM PORTFOLIO"

## TODO
- [x] discuss with @theprofessora if all "old" spinners should be replaced with the new one?
- [x] Create a new component for the new Spinner if the old one should not be replaced
- [x] Get a list for all pages/views/components where the new spinner should be implemented if the old one should not be replaced

**Comment by jabby09** [comment]
hi @theprofessora here is the first of a series of UI implementation issues where we require some analysis, recommendations, and standardization.

Please advise if you need more clarification and / or examples. The examples here in this ticket are more related to buy/retire flows, however, we also often need processing/loading spinners for other pages and features. For example, a new use case is the `Download PDF` button on the retirement receipts. When you click that button the pdf creation process can take many seconds with no communication to the user.

Ideally we settle on one universal design for loading/processing spinners that can be a component and used across the site regardless of the use case.

**Comment by theprofessora** [comment]
@jabby09 @ladytrekker Okay I've been thinking about it and given:

1. we already have so many instances of the little blue spinner (old spinner)
2. we need iterations of that spinner that exist in non-modal contexts

Here's the design decision:

let's just keep the old spinner. 

Use our bright blue brand color when the background is white or gray. 

then when the background is dark, we'll use our yellow brand color. for example, the download pdf btn, which has a dark background. 


![Image](https://github.com/KlimaDAO/klimadao/assets/110631623/8ed2ed40-23fe-40e2-8027-97d530a5ff3f)


we can place the spinner right inside the btn so the user knows that the download is pending

**Comment by jabby09** [comment]
> Here's the design decision:
> 
> let's just keep the old spinner.
> 
> Use our bright blue brand color when the background is white or gray.

@theprofessora sounds good, are these options in the components section of figma design system?

and just to clarify, does that mean this iteration goes away?
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/268f1144-65bd-4664-997d-e693897210b7)

**Comment by theprofessora** [comment]
Yes, that iteration goes away.

yes, these options are in the components section: https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN?node-id=0:1#475600489

**Comment by jabby09** [comment]
### Dev Requirements

We are standardizing on one type of processing spinner in Carbonmark. There are two colour variations:
- Our bright blue brand color when the background is white or gray
- When the background is dark, we'll use our yellow brand color
- Components [design link here](https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN?node-id=0:1#475600489)
- Believe these are the existing components
Spinner: https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/components/shared/Spinner/index.tsx
SpinnerWithLabel: https://github.com/KlimaDAO/klimadao/tree/staging/carbonmark/components/SpinnerWithLabel

- [ ] In the Processing Payment modal in the "Retire from Portfolio" flow, remove the existing processing spinner and replace with blue variation
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/397370d4-40d5-4111-814b-51e9f5f0e37d)

- [ ] On the Login modal, if you choose a social or email option, we are still showing the klima green spinner. Would be great to finally get that replaced with the carbonmark blue spinner.
