### ISSUE TITLE
[carbonmark] Align all project header images

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1217]
## Problem

The image at the top is not rounded in the corners and doesn't extend to the edges. 
This ticket happened because of this [comment here](https://github.com/KlimaDAO/klimadao/pull/1191#issuecomment-1592159186)

## Old Design
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/4fc67aab-a878-41bb-a08e-fc5de3760fa2)

## New Design
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/8e2ac6b8-92e4-4585-99a0-d7ef0a1393d7)

## TODO
- [x] go over all pages where the project header is rendered (Single project, Purchase, Retire etc etc)
- [x] Align all project headers with the same design (see [figma](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=11-59688&t=fmljhFwUor9SUvWi-0))
- [x] Check if you can create a re-usable component and use this on all occasions

**Comment by theprofessora** [comment]
Okay everything has been aligned in the figma. Here's the master component (notice the variations for different use cases): https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN?node-id=0:1#475442520

A few things to note:
1. The project image itself has no rounded corners. We're achieving this effect by rounding the card itself and clipping any overflow content.
2. On mobile, the project ID# and project name text styles change
3. The retirement forms have "*Required field" indicators, because they also have non-required fields. Since every field in the **purchase** forms is required, there are no "*Required Field" indicators.
