### ISSUE TITLE
[buy from project pool] Make pages accessible

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1219]
## Description

With this PR https://github.com/KlimaDAO/klimadao/pull/1191the main work on "buy from project pool" is done.

You can access the pages here:

- **BCT (default)** https://carbonmark.com/projects/VCS-191-2008/purchase/pools/bct
- **NCT** https://carbonmark.com/projects/VCS-981-2014/purchase/pools/nct

Still, the link from a project pool "Buy now" is still pointing to the main KlimaDao App.

## TODOs

- [ ] Is the price calculation from the API correct? See https://github.com/KlimaDAO/klimadao/issues/1156
- [ ] Double check the fee calculation again
- [ ] link the button "buy now" to the correct page

**Comment by Atmosfearful** [comment]
As far as I can think, we can link the buttons together and address the pricing in a follow up-- unless you think something is blocking that I'm forgetting @ladytrekker
