### ISSUE TITLE
[retire from pool] Pay with Credit card

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1234]
Updated [figma designs here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=890-29468&mode=design&t=JLl8iTo1R7ThUqRz-4).

See docs (https://checkout.offsetra.com/) for API documentation if required.

`Stretch goal:` during form validation, fetch the balance of the amount of USDC in the offsetra server wallet which then may allow / support transactions greater than 2000. Please reach out to @Atmosfearful to discuss in more detail.

Note that designs are provided for desktop and mobile screens.

**QUESTIONS:**

Why not move the selection of the payment method to the top of the form?
Because depending on which method the user selects, the text changes, the validation changes etc....

## TODOS
- [x] deploy Transaction Payment code to Offsetra production (currently only on Staging)
- [x] Change Logo on Stripe

## Requirements

- [x] Pay with credit card will be supported for `RETIRE NOW` function on **pool listings only**.
![Screenshot 2023-06-26 at 1 37 39 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/d2ca58af-bfff-418f-a1bf-82660364ca7f)

- [x] In the `RETIRE NOW` on pool listings flow, the **Pay with** dropdown needs to be updated to support selecting Credit Card. Note that for all other BUY and RETIRE flows, the Credit Card option in the dropdown will remain greyed out with Coming Soon notation.
![Screenshot 2023-06-26 at 1 38 13 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/7570d17b-214d-4cb0-adc9-f5f2f306ba61)

- [x] When the user selects Pay with Credit Card, the description above the drop down changes from Balance xxxxx to $2,000 maximum for credit cards
![Screenshot 2023-06-26 at 1 38 44 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/386584ba-b8e5-439b-a6db-18949227a94a)

- [x] As the user selects the number of tonnes to retire, the form will need a validation to ensure the total cost does not exceed $2,000. Otherwise, show the following error state:
![Screenshot 2023-06-26 at 1 39 07 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/32fb0703-8923-49b1-91d3-c13886863437)

- [x] CAUTION: Only integers are allowed as tonnes

- [x] Assuming the form does not have validation errors, clicking CONTINUE will bring up the Confirm Purchase modal and Stripe redirection note. 

- [x] Clicking CONTINUE on the confirm modal directs the user to the Offsetra/Stripe payment confirmation page. You may need to access the [API documentation](https://checkout.offsetra.com/) to make changes to this page.

- [x] On the [payment confirmation page](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=890-35887&mode=design&t=KN9kOGTsLFLxnv68-4), need to swap out the KlimaInfinity logo for Carbonmark logo. May need to update the Powered by...content 

- [x] After clicking PAY and the transaction is successful, the user will be directed to [transaction complete page](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=892-31568&mode=design&t=KN9kOGTsLFLxnv68-4). Changes required:
- "Return to klimadao.finance and off more carbon." should be changed to "Return to carbonmark.com and off more carbon." The carbonmark.com link should be set to https://www.carbonmark.com/projects
- Swap out the KlimaInfinity logo for Carbonmark logo.
