### ISSUE TITLE
[credit card] Retire 1 tonne throws error on Production

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1317]
## Description

🔥 **OPEN TODO: DEPLOY OFFSETRA STAGING TO PRODUCTION** (see comments below)

See this default pool project on Carbonmark:
https://www.carbonmark.com/projects/VCS-191-2008/retire/pools/bct

When trying to retire 1 tonne, the Offsetra Production API throws with a Gas Estimation Error.

Interestingly, this does not happen on Staging when running against the Offsetra Staging API:
https://staging.carbonmark.com/projects/VCS-191-2008/retire/pools/bct

Even when running locally and faking the Offsetra API to be on "production" it does not fail.

## Assumption
- [x] price is too low for the Production Server Wallet on Offsetra?

## TODO
- [x] Offsetra: extend the error log for this Gas Estimation error and send the message down to the client
- [x] Offsetra: Deploy Offsetra Staging to Offsetra Production
- [x] Provoke the error again

**Comment by Atmosfearful** [comment]
Not able to reproduce this...

**Comment by ladytrekker** [comment]
Happen only when the BCT price is very low.
Currently it happens for the price per tonne $0.91

Production Offsetra API Error if you enter only 1 tonne:
=> https://www.carbonmark.com/de/projects/VCS-498-2011/retire/pools/bct

Not happening on Staging for the same project:
=> https://staging.carbonmark.com/de/projects/VCS-498-2011/retire/pools/bct

Now, with the deployed error trace on the Offsetra Server, this is the exact error:

`trace: maxCosts: 0.92, error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason=\"execution reverted: UniswapV2Router: EXCESSIVE_INPUT_AMOUNT\", method=\"estimateGas\"`

<details>
  <summary>**### Click HERE to see full error**</summary>
  
  ```TS
  {
      name: "GasEstimateFailed"
      message: "The price could not be estimated. Double-check the desired inputs. This may be due to an incompatible project selection or insufficient quantity. trace: maxCosts: 0.92, error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason=\"execution reverted: UniswapV2Router: EXCESSIVE_INPUT_AMOUNT\", method=\"estimateGas\", transaction={\"from\":\"0xfB079f82cdD18313F3566fb8dDd6414B3507bDA2\",\"to\":\"0x8cE54d9625371fb2a068986d32C85De8E6e995f8\",\"data\":\"0x2eb3eb0a0000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000002f800db0fdb5223b3c3f354886d907a671414a7f0000000000000000000000000115ab6d9a0fd6de3a9a339115c8f2bd0e3deed600000000000000000000000000000000000000000000000000000000000e09c00000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000fb079f82cdd18313f3566fb8ddd6414b3507bda2000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b706c616365686f6c646572000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b706c616365686f6c646572000000000000000000000000000000000000000000\",\"accessList\":null}, error={\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":49,\\\"error\\\":{\\\"code\\\":3,\\\"data\\\":\\\"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000027556e69737761705632526f757465723a204558434553534956455f494e5055545f414d4f554e5400000000000000000000000000000000000000000000000000\\\",\\\"message\\\":\\\"execution reverted: UniswapV2Router: EXCESSIVE_INPUT_AMOUNT\\\"}}\",\"error\":{\"code\":3,\"data\":\"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000027556e69737761705632526f757465723a204558434553534956455f494e5055545f414d4f554e5400000000000000000000000000000000000000000000000000\"},\"requestBody\":\"{\\\"method\\\":\\\"eth_estimateGas\\\",\\\"params\\\":[{\\\"from\\\":\\\"0xfb079f82cdd18313f3566fb8ddd6414b3507bda2\\\",\\\"to\\\":\\\"0x8ce54d9625371fb2a068986d32c85de8e6e995f8\\\",\\\"data\\\":\\\"0x2eb3eb0a0000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000002f800db0fdb5223b3c3f354886d907a671414a7f0000000000000000000000000115ab6d9a0fd6de3a9a339115c8f2bd0e3deed600000000000000000000000000000000000000000000000000000000000e09c00000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000fb079f82cdd18313f3566fb8ddd6414b3507bda2000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b706c616365686f6c646572000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b706c616365686f6c646572000000000000000000000000000000000000000000\\\"}],\\\"id\\\":49,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"https://polygon-mainnet.infura.io/v3/dff93611cbeb477bafaf8aeb6004132a\"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)"
 }
```
</details>

**Comment by ladytrekker** [comment]
## Update

On the Offsetra Side this was merged to Staging:
- Increase the slippage from 0.05% to 0.1%
- Make sure to estimate gas for the same values on Staging as well as on production (to ensure we get the same errors on both environments)

Tested it with several currently throwing projects:

**FAILING with Offsetra Production:**
https://www.carbonmark.com/de/projects/VCS-498-2011/retire/pools/bct

**SUCCESS with Offsetra STAGING (now with the same estimation code)**
https://staging.carbonmark.com/projects/VCS-498-2011/retire/pools/bct

## TODO
- [ ] deploy Offsetra Staging to Offsetra Production
- [ ] => error should not appear again

**Comment by Atmosfearful** [comment]
Fixed merged to prod in the Fiat repo ✅
