### ISSUE TITLE
[Transaction Fees] Extend with Credit Card breakdown, move to Docs

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1351]
## Description 

Related to https://github.com/KlimaDAO/klimadao/issues/1344

The fee calculation is very complex and should be documented correctly.
Right now, the fees breakdown when paymentMethod is "USDC" is documented in[ this WIKI page](https://github.com/KlimaDAO/klimadao/wiki/Buy-(Redeem)-and-Retire-Fees-Summary)

As it is now possible to pay with credit card too, these fees have to be documented as well.

### TODO
- [ ] Extend [this WIKI page](https://github.com/KlimaDAO/klimadao/wiki/Buy-(Redeem)-and-Retire-Fees-Summary) with the Fee breakdown when payment method is "fiat" (Paying with credit card)
- [ ] Move this page to the official Docs
- [ ] Discuss if the transaction views in Carbonmark should rather link to this newly created docs page than displaying a fee breakdown ("Want to know how the fees are calculated? Click here") 

## Sidenote
This PR hides all fees => https://github.com/KlimaDAO/klimadao/pull/1350
When the decision above results in not showing a fees breakdown at all anymore in Carbonmark, please ensure to remove the SHOW_FEE toggle and all related code accordingly in a follow-up PR.
