### ISSUE TITLE
[EPIC] Klima Infinity Pledge dashboard

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#255]
#### Feature branch for epic
https://github.com/KlimaDAO/klimadao/tree/klima-infinity-pledge-dashboard

A shareable, search-indexable dashboard.
- shows your carbon assets and retirements
- allows you to connect your wallet, edit the pledge name/description/methodology and footprint.
- charts show your total balances over time

Designs [in figma.](https://www.figma.com/file/krpWuauhMXxgNBcvkPqP3q/Klima-Infinity-DASHBOARD?node-id=125%3A1500)

TODO:
- [x] Get subgraph endpoint and/or relevant contract addresses from and integrate data using `getStaticProps` @0xAeterno 
  -  We don't need subgraphs for v0.5, just when we add the charts/graphs
- [x] Create basic layout without any graph or charting libraries (just pledge data read/write, and contract/graph data)
- [x] Mobile + desktop views

**Comment by 0xAeterno** [comment]
> * [x]  The 0x address of the pledge should always be visible somewhere. It acts as the fallback when there is no name. But when there is a name, we need to show it somewhere (DESIGN NEEDED).

A concatted address is always visible on a pledge regardless of whether or not there is an pledge tied to address :)
