### ISSUE TITLE
Bonds v2 migration

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#395]
Bond contracts have been upgraded, we need to migrate the app to use these new contracts.
The new contracts have a slightly different API.
* [ ] DESIGN NEEDED: Implement design/UX to allow a v1 bond redemption, which should only appear if the user has a redeemable v1 balance or pending bond.
- The UI will support both v1 and v2 redemptions, but new bonds will all be v2
- V2 will have a testnet up and running

# Old API
Complete implementation is here:
https://github.com/KlimaDAO/klimadao/blob/b1469fc32a534c5f89bacfc074637e561999089f/app/actions/bonds.ts#L141
## Calculating bond details
Our app uses the following methods on the `bond` and `bondCalc` contracts.
```ts
const terms = await bondContract.terms();
const maxBondPrice = await bondContract.maxPayout();
const debtRatio = await bondContract.debtRatio();
const bondPrice = await bondContract.bondPriceInUSD();
const bondDetails = await bondContract.bondInfo(address);
const pendingPayout = await bondContract.pendingPayoutFor(address);
const valuation = await bondCalcContract.valuation(
  tokenAddress,
  value
);
const quote = await bondContract.payoutFor(valuation)
```
## Creating a bond
```ts
const txn = await bondContract.deposit(value, maxPremium, address);
```
## Redeeming a bond
```ts
const txn = await bondContract.redeem(address, autostake);
```

# New API
## Calculating bond details
TODO: @cujowolf @0xAurelius 
## Creating a bond
TODO: @cujowolf @0xAurelius 
## Redeeming a bond
TODO: @cujowolf @0xAurelius 

# Implementation plan
* [ ] Add v2 ABIs
* [ ] Update redux state to store both pending v1 and pending v2 bonds. v1 state is necessary so we can show the proper UI when the user has a pending v1 bond
* [ ] Re-write actions
* [ ] Support Testnet for v2 bonds.
  #2 
  * [ ] add testnet contracts
  * [ ] the 'switch network modal' should NOT appear when the user is on mumbai
  * [ ] update all bond v2 actions to support the runtime network

**Comment by jabby09** [comment]
[cujo]
Might still need this one if we wanted to us v2 bonds whenever bonding opens up. But that's a big who knows timeline wise.
I'd personally be fine with closing/re-opening if needed. The main structure is already there for the inverse bonds we did

[shimon]
Regarding #395, this is completely separate from the RA v2. 
I think @Archimedes (10,10) | (3,3) was working on adding v2 bonds, so I'll defer to him.
I personally don't think we need to worry about v2 bonds until we can reopen v1 bonds.
