### ISSUE TITLE
Single Retirement Page: Show link to project

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#438]
## Enhancement

Query all project data from the tokenAddress of the Offset and show a link to:
- Project on Verra
- Project Type
- Methodology
- Project Name

## TODO
- [x] verify that this is wanted
- [x] discuss where to show this data on the page (design)
- [x] implement it

**Comment by Atmosfearful** [comment]
Otherwise, we are good to go. I would display it as such in the UI (for bct, nct, ubo, nbo):
```
Project Details
(PROJECT_NAME)[hyperlink that takes you to the verra page]
(TOKEN NAME)[link to token on polygonscan]
```
For example
```
Project Details
DiangJiang Hydropower Phase2
TCO2-19-2008
```

# Later on
* [ ] indicate selective retirement (those which were offset using the "advanced" selection). @0xAurelius will let us know if or how this is possible, right now he isn't sure.

# Far future
Some how pull the map data and render a map :)

**Comment by 0xAurelius** [comment]
Note that individual retirement events can be comprised of multiple individual Offset entities

Gotta make sure we can display one or more offset projects on a given page

**Comment by Atmosfearful** [comment]
> Note that individual retirement events can be comprised of multiple individual Offset entities
> 
> Gotta make sure we can display one or more offset projects on a given page

OOH good catch. How does the response from the graph look like when a retirement has multiple projects?

UI should display them in a simple list

**Project Details**
[4×50 MW DAYINGJIANG- 3 HYDROPOWER PROJECT PHASES 1&2](https://registry.verra.org/app/projectDetail/VCS/191)
[TCO2-191-2008](https://polygonscan.com/token/0xb139c4cc9d20a3618e9a2268d73eff18c496b991?a=0x2f800db0fdb5223b3c3f354886d907a671414a7f)
32.123 Tonnes

[Another different project name](https://registry.verra.org/app/projectDetail/VCS/191)
[TCO2-123-2022](https://polygonscan.com/token/0xb139c4cc9d20a3618e9a2268d73eff18c496b991?a=0x2f800db0fdb5223b3c3f354886d907a671414a7f)
110 Tonnes

[Third project name](https://registry.verra.org/app/projectDetail/VCS/191)
[TCO2-123-2022](https://polygonscan.com/token/0xb139c4cc9d20a3618e9a2268d73eff18c496b991?a=0x2f800db0fdb5223b3c3f354886d907a671414a7f)
2 Tonnes

**Comment by Atmosfearful** [comment]
https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk/CARBON-OFFSETTING?node-id=5%3A835

**Comment by ladytrekker** [comment]
## Update

I am retrieving the data for a single project with the subgraph "projectID" now directly from Verra 👍 
Here is the [draft PR](https://github.com/KlimaDAO/klimadao/pull/447).

**Open Questions:**

Where can I find an example on how the data would like like when a projectID has multiple Offset entities?
@0xAurelius 
Would this be reflected in the subgraph data somewhere? 
Or in the Verra data (see the data types [here](https://github.com/KlimaDAO/klimadao/blob/798ffd84282162b0f9e5534a5e90ac6f5fb808c9/lib/types/verra.ts))?
Do you know of any retirement examples?

The design link is not pointing to a specific file.
I took now the latest screen I found on Figma => see [link](https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk/CARBON-OFFSETTING?node-id=1014%3A1449).
@Atmosfearful Can you tell me what the final design should be? 
The current one has colors which are new and fonts which are different?

**Comment by 0xAurelius** [comment]
ok sorry I was a little confused about how the implementation works for multiple-project retirements

so when a user issues a retirement that consumes credits from multiple projects, the contract generates multiple retirement events, one for each offset token consumed

So if you did 100 BCT selective retirement and it was split 75/25, you’ll actually add 2 to the index and have one retirement that’s 75 and one that is 25

Though on the subgraph we could tie them together with the tx hash, let's keep it simple for now and just have multiple pages, one for each value of the index

**Comment by ladytrekker** [comment]
> 

Ok, thanks. Then it already works with the current implementation.
