### ISSUE TITLE
[bonds] Move bonds allowance to allowances redux state

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#627]
### Description

This is the last piece missing after:
- https://github.com/KlimaDAO/klimadao/issues/579
- and the corresponding PR https://github.com/KlimaDAO/klimadao/pull/600

### TODO
- [ ] move bonds allowances to `user.allowances` state 
- [ ] ensure that the sorting of allowances and spender is correct
- [ ] adjust the selectors accordingly
- [ ] test if everything still works
- [ ] remove unused code
