### ISSUE TITLE
CMS content: Use new tags and featured flag in Sanity

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#647]
## Description

The resources page will be re-build from the ground up with a filter and sorting and search functionality 
for **posts and podcasts.**
Additionally, Featured Articles (**posts**) are shown in a Slider on the top of the page.

# Tags

To enable a filter functionality for posts and podcasts, the CMS was extended with a new type => "Tags"
Now each and every **posts and podcasts** has to be referenced with **at least one tag.**

### TODO:
- [x] create new meaningful tags (the names will appear later as the filter functionality on the Site and should be short and crispy), see screenshot below
- [x] attach at least one tag (or more) to every **posts and podcasts** (see screenshot below)

**NOTE:**
In the [Design](https://www.figma.com/file/NQTGQDrS7PEfB3QOzYMBN3/RESOURCES?node-id=1405%3A408) these are the TAG names:
 „Klima Infinity, Overview, Partnerships, Announcement, Press Release, Basics, User Guide, Policy"
=> **Please use the same names or discuss with design if you want to change them and tell the devs later the final names of tags**

### UPDATE 🧨 

**The final tag list:**

- Klima Overview
- Klima Infinity
- Partnerships 
- Basics 
- Deep Dives 
- User Guides 
- Press Releases
- Policy 
- Carbon Footprint 

# Featured Articles

The new page will have a slider on top with "featured articles".
To distinguish between which **post** is a featured one and which is not, the cms was extended with a new checkbox => "Is featured Article"

### TODO:
- [ ] go over relevant **posts** which should appear in the slider and enable the checkbox (see screenshot below)
- [ ] or create new posts and enable the checkbox
- [ ] Ensure that all these posts do have a nice image **without any text on top!**

# Screenshots

### CREATE A TAG (every field is required)

<img width="1792" alt="Bildschirmfoto 2022-08-31 um 15 39 01" src="https://user-images.githubusercontent.com/95881624/187692278-feaff586-0a61-4a95-876e-dd32f7b049b3.png">

### ADD TAGs TO A POST / PODCAST

<img width="1784" alt="Bildschirmfoto 2022-08-31 um 15 40 31" src="https://user-images.githubusercontent.com/95881624/187692615-ef648ae7-2c42-4849-80fe-c4f463522f28.png">

### FLAG A POST as "FEATURED"
<img width="1789" alt="Bildschirmfoto 2022-08-31 um 15 41 41" src="https://user-images.githubusercontent.com/95881624/187693065-64fc7a14-065e-4a01-a3f5-704d088029b1.png">

## Related Ticket

https://github.com/KlimaDAO/klimadao/issues/534

**Comment by jabby09** [comment]
this work stream is complete.
