### ISSUE TITLE
Resources: Go live 🎉 

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#760]
## Todos for GO LIVE to production

- [x] change link on individual blog pages from `/blog` to `/resources`
- [x] remove links "blog" and "podcast" from "About" sub-navigation in main nav
- [x] add link "Resources" to "About" in sub-navigation in main nav accordingly (or "Latest news" because "Resources" already exists? => **see Screenshots below**)
- [x] in` site/next.config.js` remove redirect from "resources" to "blog"
- [x] in` site/next.config.js` add redirects from "blog" to "resources" and "podcast" to "resources"
- [x] delete all unused components and other files for pages `/blog` and `/podcast`

### PREVIEW LINK

STAGING (merged code status): https://staging-site.klimadao.finance/resources

### DESIGN
https://www.figma.com/file/NQTGQDrS7PEfB3QOzYMBN3/RESOURCES?node-id=5%3A833

### RELATED TICKETS

https://github.com/KlimaDAO/klimadao/issues/534

**Comment by ladytrekker** [comment]
### QUESTION

How to integrate the new page "/resources" into the main navigation?

### Problem: "RESOURCES" already exists

<img width="1202" alt="main_nav" src="https://user-images.githubusercontent.com/95881624/198830185-51b0b6b4-2370-48f0-af4e-8ebd82f673a5.png">

### Idea: Call it "Latest News" in submenu of "About"?

<img width="1162" alt="nav_blog" src="https://user-images.githubusercontent.com/95881624/198830381-cba2cbb0-9f59-4ec4-99e7-6679a0b31071.png">


<img width="1180" alt="community" src="https://user-images.githubusercontent.com/95881624/198831275-c14e8275-b342-458a-bef0-178d2f4279c2.png">
