### ISSUE TITLE
Never use white-text-over-Klima-Green

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#880]
we must pay the price of rushed design decisions pre-launch (choosing this as our primary color 🤮 )

Typically we have "primary font" color which is white in light mode, black in dark mode. But because of color-contrast concerns, we must now use a different color when klima-green is our background. 

Related to @ShimonD-KlimaDAO 's note here: https://github.com/KlimaDAO/klimadao/pull/834#issuecomment-1377781060

And a discussion in discord here:
https://discord.com/channels/841390338324824096/964698337230086174/1059953750820790354

# Task
As far as I know this only applies to buttons, so lets start there
* [ ] the top right button in the site
* [ ] the confirmation / connect buttons in the app (top right, but also seen in the retirement ui and elsewhere)
* [ ] buttons on the /retirement pages
![image](https://user-images.githubusercontent.com/88635679/212184482-c25d3a59-d8bb-473b-ace7-aa1a43b01893.png)

# Pass
![gud](https://cdn.discordapp.com/attachments/964698337230086174/1060275413856833617/image.png)

# Fail
![bad](https://cdn.discordapp.com/attachments/964698337230086174/1060275118485545090/image.png)
