### ISSUE TITLE
[translations] Try SWC plugin for lingui, remove babel

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#922]
New lingui swc-plugin https://github.com/lingui/swc-plugin

SWC should give us faster builds. https://nextjs.org/docs/advanced-features/compiler#why-swc

# Preliminary research
* [x] aside from lingui, what else needs babel? Can we remove @emotion/babel-plugin?

# Todos
* [x] npm install the lingui swc plugin it for app and site
* [x] Using the `swcPlugins` field in `next.config.js`  update config to use the swc lingui plugin for app and site
* [x] delete babel config and any other babel stuff
* [ ] see if the builds are faster and document the difference in speed (I can provide vercel access to view builds)

**Comment by biwano** [comment]
Without swc

```
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/biwano/code/klimadao/app/.babelrc
event - compiled client and server successfully in 65.5s (12420 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 36.5s (12999 modules)
```

With swc

```
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
warn  - You have enabled experimental feature (swcPlugins) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

event - compiled client and server successfully in 42s (12394 modules)
wait  - compiling / (client and server)...
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 33.7s (12969 modules)
```

**Comment by biwano** [comment]
@Atmosfearful If we are still doing this, I need to add the code to carbonmark too.

**Comment by Atmosfearful** [comment]
This was tested here https://github.com/KlimaDAO/klimadao/pull/927
But no significant speedup was detected so we will stick with the tried-and-tested babel builds
