### ISSUE TITLE
[sanity] Set tag "klima-overview" as default

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#934]
## Description

Content manager are tagging almost every post with the tag "klima-overview"

Now they ask the question, why not set the catgeory/tag "klima-overview" as a default on the /resources UI?

See Page https://www.klimadao.finance/resources

![Screenshot_2023-02-21_at_9](https://user-images.githubusercontent.com/95881624/220368822-e107aff5-660f-4c04-9d99-3b654ecf618b.png)

## Questions
-  What is the main goal to achieve when enabling this tag/category by default when the UI shows all recent posts anyways of which the majority is tagged with "klima-overview" already?
- Why narrow down the visible selection which then might mot be the most recent updated collection of posts?
- What should happen with the "Clear all" button? Remove all filters? Keep "klima-overview" checked?
- When "klima-overview" is the default => the newest latest post may not be visible when it does not have the same tag
- When almost every post has this category => is this category even needed 🤔 ? Why is every post a "klima-overview" post? 

## TODO
- [ ] discuss all possible scenarios above
- [ ] depending on decision: change the query in getStaticProps for the resources page
- [ ] depending on decision: change the defaultValues for the resources filter checkbox group and form
- [ ] ensure everything works no matter what the user selects

**Comment by jabby09** [comment]
@rittaaka questions below...can you please provide additional information?

1. What is the main goal to achieve when enabling this tag/category by default when the UI shows all recent posts anyways of which the majority is tagged with "klima-overview" already?
2. Why narrow down the visible selection which then might mot be the most recent updated collection of posts?
3. What should happen with the "Clear all" button? Remove all filters? Keep "klima-overview" checked?

Also note that when "klima-overview" is the default => the newest latest post may not be visible when it does not have the same tag.

**Comment by rittaaka** [comment]
Hi Jabby,

1. The UI does not currently show all recent posts tagged "klima-overview".
If you land on klimadao.finance/resources, you see "Recent literature on
KlimaDAO and the Digital Carbon Market" (1/20/2023) and then "Download
KlimaDAO’s ‘Introduction to the Digital Carbon Market’" (12/15/2022).
However multiple blogs are missing, e.g. "ON SET #1 – recording, takeaways,
FAQs"., "Law Commission Call for Evidence on DAOs", "KlimaDAO and SCB Group
Carbon Project Financing Partnership", and more, which are tagged
"klima-overview" but are missing

2. As per 1., the current display is not showing the most recent blogs

3. If "Clear all" is checked, "klima-overview" can be unchecked.

**Comment by jabby09** [comment]
@rstycedar when you get to once let me know and we can kick off a discovery discussion
