### ISSUE TITLE
[epic] List view in Carbonmark

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#976]
This epic is to complete the implementation of the List View of the Marketplace in Carbonmark. It is broken down into a series of tasks.

The overall [design is here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?node-id=11-58349&t=XpMuKoZSl73STBEx-4).

**NOTE:** _[Updates to the filter and sort interface](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?node-id=268-19204&t=XpMuKoZSl73STBEx-0) are in progress and may change some aspects of implementation of the List View._

**Comment by jabby09** [comment]
- [ ] Add Card/List toggle on Marketplace header
- [ ] another sub task
- [ ] another sub task
