### ISSUE TITLE
[activities] Show Handle name

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#988]
## Description

Where should the hyperlink from the seller/buyer addresses go to?
=> Always go to carbonmark.

It may be the case that they don't have a profile created yet, but at least then you can explore their other past activity and see their balances.

~No kns/ens lookup, this is not super relevant for carbonmark users now that we have handles (only klima / defi nerds)~

But showing the handle would be nice, if the API gives it to us. Not a must-have for v1.

## TODO
- [x] check with API dev if handle can be added to the data
- [x] or look it up on the client
- [ ] if buyer/seller is a carbonmark user => show handle instead of truncated address

<img src="https://user-images.githubusercontent.com/7104689/213628391-072ad450-795a-495d-8813-826b6b8468d4.png" width="300" />

**Comment by psparacino** [comment]
> @psparacino see my comment above and let me know if you think this is something you can take on

Sounds good! Looks like I'm already assigned so I'll begin on it
